### ISSUE TITLE
There is no way to customize the icon style in Tooltip component 

### ISSUE THREAD

**Issue by ilovepumpkin** [carbon-design-system/carbon-components-react#226]
Now my requirement is to display a red "info" icon with tooltip. I checked the current Tooltip component, but it can not meet my requirements - It does not allow me to customize the icon style. Is it possible to add a style object to iconClassName prop so that I can customize the style of the icon?

**Comment by WilliamHolmes** [comment]
A workaround would be to wrap the tooltip component in your own container and override styles.
e.g.
```javascript
<div className={'info_class'}>
   <Tooltip>{'some content'}</Tooltip>
</div>
```
... (sass)
```css
.some_class {
  .bx--tooltip__trigger {
    svg {
       fill: red;
    }
  }
}
```
