### ISSUE TITLE
Required Input fields render a red border in Firefox

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-components-react#304]
Was digging into the two Firefox related issues in #141 #290 and it seems like the following is a part of Firefox's UA stylesheet:

```css
/**
 * Set default style for invalid elements.
 */
:not(output):-moz-ui-invalid {
  box-shadow: 0 0 1.5px 1px red;
}

:not(output):-moz-ui-invalid:-moz-focusring {
  box-shadow: 0 0 2px 2px rgba(255,0,0,0.4);
}
```

_Mentioned in [this issue](https://github.com/twbs/bootstrap/issues/21323#issuecomment-266169875) in Bootstrap_

---

This issue is for resolving the issue report in #141 and #290 for input elements that display the red outline when the `required` attribute is specified.
