### ISSUE TITLE
Combining an overflow menu with a table causes an outline that extends across rows in Firefox

### ISSUE THREAD

**Issue by zgrossbart** [carbon-design-system/carbon-components-react#841]
Combine an overflow menu with a table like this:

![screen shot 2018-04-26 at 12 07 38 pm](https://user-images.githubusercontent.com/664044/39317811-86fa8120-494a-11e8-93e5-960b82a75411.png)

Now click on the overflow menu.  On Chrome this looks like this:

![screen shot 2018-04-26 at 12 09 13 pm](https://user-images.githubusercontent.com/664044/39317878-afa22786-494a-11e8-8145-1f9c445ef4df.png)

Note that the selection outline just extends around the row.  

On Firefox it looks like this:

![screen shot 2018-04-26 at 12 05 24 pm](https://user-images.githubusercontent.com/664044/39317919-c30775c4-494a-11e8-9b29-69fb95f4295a.png)

Note that the outline extends around multiple rows making it confusing which row is selected.

This happens because of the following CSS from Carbon components:

```css
.bx--table-body .bx--table-row:not(:first-child):hover, .bx--table-body .bx--table-row:not(:first-child):focus {
    border-left: 2px solid #5596e6;
    outline: 1px solid #5596e6;
}
```

The problem is that Firefox interprets the `outline` property to extend all the way around all of the contents of the row.  The fix for this either needs to stop using the `outline` property and use `border` or some other property instead, or position the menu so it isn't a child of the row in the DOM.
